global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.26.11:9090','172.31.27.240:9100','172.31.20.35:9100'] ##Port 9090 is the default Prometheus Port while Port 9100 is the port for Node Exporters
